[package]
name = "klask"
version = "1.0.0"
authors = ["Micha≈Ç Gniadek <mgniadek@interia.pl>"]
edition = "2018"
license = "MIT"
description = "Automatically create GUI for clap apps"
repository = "https://github.com/MichalGniadek/klask"
categories = ["gui"]
keywords = ["clap", "gui", "ui", "cli", "egui"]

[dependencies]
Inflector = { version = "0.11.4", default-features = false }
clap = { version = "=3.0.0", default-features = false, features = [
    "std",
    "derive",
    "unicode",
] }
clap_derive = { version = "=3.0.0" }
uuid = { version = "0.8.2", features = ["v4"] }
cansi = "2.1.1"
eframe = { version = "0.18.0", default-features = false, features = [
    "default_fonts",
] }
linkify = "0.8.1"
thiserror = "1.0.31"

[target.'cfg(not(target_os = "windows"))'.dependencies]
native-dialog = "0.6.3"

# Should make dialogs look better
[target.'cfg(target_os = "windows")'.dependencies]
native-dialog = { version = "0.6.3", features = [
    "windows_dpi_awareness",
    "windows_visual_styles",
] }
